### ISSUE TITLE
Any way to change the image "temp" directory?

### ISSUE THREAD

**Issue by AKL55** [Gunbard/ThumbThumb#1]
Just want to change it to my hard drive instead of ssd.

**Comment by Gunbard** [comment]
That would be controlled by [vsci](https://github.com/amietn/vcsi/blob/f358c7e3e4d927e53314977fa7456fa8b98b6ba0/vcsi/vcsi.py#L697C9-L697C9), which doesn't appear to currently expose setting the tempfile directory. If you really need it, the docs for the tempfile Python library say you might be able to do it by setting your system's TMPDIR, TEMP, or TMP environment variables: https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp
